### PR TITLE
Reformat

### PR DESCRIPTION
**Pull request by dalonsoa**
Mostly using linters and code formatters (black, isort, flake8) to reformat the code following standards. Lot's to do on this, yet, but is a first pass.

### CODE REVIEW

**Comment by dalonsoa** [comment]
@phoebe-p , more than to actually reviewing the code (please, go ahead if you want!), which is a total mess at the moment, is to highlight that I've transfer Sunglass to the QPV group GitHub and that I'll be working on this in the near future rather than on Solcore itself. Please, try to install it and running following the instructions in the README fro developers and let me know if you get something that looks like this:

image

**Comment by phoebe-p** [comment]
Hi @dalonsoa I missed this initially among the other emails from GitHub - I just successfully installed this in developer mode (first time using Poetry, seems like a useful tool). I had some weird issues:

1. I couldn't install scipy==1.6.1. The current version (1.9.2) works fine, I guess because there are Apple Silicon wheels for it; the 1.6.1 has to be built from source and I don't have the relevant libraries installed. Seems like this is definitely fixable but I am not sure if there is a reason for using an older version of scipy?
2. After the scipy issue was "fixed" by just running `pip install scipy` (after running `poetry shell`), the installation failed on installing solcore because it was complaining numpy was not installed. Even after I did `pip install numpy`, it still had this complaint (?), but just running `pip install solcore` outside of `poetry install` was fine (weird). 

So after these small issues, everything worked and I get a screen like the one you showed above, although I didn't spend much time testing it.

**Comment by dalonsoa** [comment]
Hi Phoebe, no worries!

1. I've no idea where this pining is coming from. `sunglass` do not depend directly on `scipy` as you can see [here](https://github.com/qpv-research-group/sunglass/blob/52baf3084dd0df9b824a5247657417dffe89a088/pyproject.toml#L10), and `solcore` does not impose any specific version, so I'm not sure why `poetry` is trying to install an old version. Will check.
2. This is really odd, however it should be solved (for most users) once we have binary wheels for the main OS and platforms (sorry about M1 processors...). It seems the order of search paths in PYTHONPATH is not correctly updated after entering into the poetry shell. Maybe next time, instead of doing `poetry shell` and then run commands there, lets try `poetry run python -m pip install numpy`, or whatever needs to be installed manually.

**Comment by dalonsoa** [comment]
@all-contributors please add @phoebe-p  for review and bug

**Pull request merged**
